/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppTransactionsRouteImport } from './routes/app.transactions'
import { Route as AppSettingsRouteImport } from './routes/app.settings'
import { Route as AppGoalsRouteImport } from './routes/app.goals'
import { Route as AppCardsRouteImport } from './routes/app.cards'
import { Route as AppAracyRouteImport } from './routes/app.aracy'
import { Route as AppAnalyticsRouteImport } from './routes/app.analytics'

const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppTransactionsRoute = AppTransactionsRouteImport.update({
  id: '/transactions',
  path: '/transactions',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppGoalsRoute = AppGoalsRouteImport.update({
  id: '/goals',
  path: '/goals',
  getParentRoute: () => AppRoute,
} as any)
const AppCardsRoute = AppCardsRouteImport.update({
  id: '/cards',
  path: '/cards',
  getParentRoute: () => AppRoute,
} as any)
const AppAracyRoute = AppAracyRouteImport.update({
  id: '/aracy',
  path: '/aracy',
  getParentRoute: () => AppRoute,
} as any)
const AppAnalyticsRoute = AppAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/app/analytics': typeof AppAnalyticsRoute
  '/app/aracy': typeof AppAracyRoute
  '/app/cards': typeof AppCardsRoute
  '/app/goals': typeof AppGoalsRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/transactions': typeof AppTransactionsRoute
  '/app/': typeof AppIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app/analytics': typeof AppAnalyticsRoute
  '/app/aracy': typeof AppAracyRoute
  '/app/cards': typeof AppCardsRoute
  '/app/goals': typeof AppGoalsRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/transactions': typeof AppTransactionsRoute
  '/app': typeof AppIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/app/analytics': typeof AppAnalyticsRoute
  '/app/aracy': typeof AppAracyRoute
  '/app/cards': typeof AppCardsRoute
  '/app/goals': typeof AppGoalsRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/transactions': typeof AppTransactionsRoute
  '/app/': typeof AppIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/app/analytics'
    | '/app/aracy'
    | '/app/cards'
    | '/app/goals'
    | '/app/settings'
    | '/app/transactions'
    | '/app/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app/analytics'
    | '/app/aracy'
    | '/app/cards'
    | '/app/goals'
    | '/app/settings'
    | '/app/transactions'
    | '/app'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/app/analytics'
    | '/app/aracy'
    | '/app/cards'
    | '/app/goals'
    | '/app/settings'
    | '/app/transactions'
    | '/app/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/transactions': {
      id: '/app/transactions'
      path: '/transactions'
      fullPath: '/app/transactions'
      preLoaderRoute: typeof AppTransactionsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/goals': {
      id: '/app/goals'
      path: '/goals'
      fullPath: '/app/goals'
      preLoaderRoute: typeof AppGoalsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/cards': {
      id: '/app/cards'
      path: '/cards'
      fullPath: '/app/cards'
      preLoaderRoute: typeof AppCardsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/aracy': {
      id: '/app/aracy'
      path: '/aracy'
      fullPath: '/app/aracy'
      preLoaderRoute: typeof AppAracyRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/analytics': {
      id: '/app/analytics'
      path: '/analytics'
      fullPath: '/app/analytics'
      preLoaderRoute: typeof AppAnalyticsRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAnalyticsRoute: typeof AppAnalyticsRoute
  AppAracyRoute: typeof AppAracyRoute
  AppCardsRoute: typeof AppCardsRoute
  AppGoalsRoute: typeof AppGoalsRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppTransactionsRoute: typeof AppTransactionsRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAnalyticsRoute: AppAnalyticsRoute,
  AppAracyRoute: AppAracyRoute,
  AppCardsRoute: AppCardsRoute,
  AppGoalsRoute: AppGoalsRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppTransactionsRoute: AppTransactionsRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
